# Generated by Django 2.2.6 on 2019-10-29 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speaker',
            name='session',
        ),
        migrations.AddField(
            model_name='speaker',
            name='session',
            field=models.ManyToManyField(blank=True, null=True, related_name='speakers', to='presentations.Session'),
        ),
    ]
