# Generated by Django 2.2.6 on 2019-10-29 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentations', '0003_auto_20191029_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='num_of_ratings',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
