# Generated by Django 2.2.6 on 2019-10-30 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('presentations', '0004_session_num_of_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='session',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='num_of_ratings',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='session',
            field=models.ManyToManyField(blank=True, related_name='speakers', to='presentations.Session'),
        ),
    ]
